//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Fanmotor.rc
//
#define ID_BUTTON_START                 3
#define ID_BUTTON_ABOUT                 4
#define ID_BUTTON_400KHZ                5
#define ID_BUTTON_200KHZ                6
#define ID_BUTTON_50KHZ                 7
#define ID_BUTTON_10KHZ                 8
#define ID_BUTTON_25KHZ                 9
#define ID_BUTTON_70KHZ                 10
#define ID_BUTTON_8KHZ                  11
#define ID_BUTTON_80KHZ                 12
#define ID_BUTTON_PWM_DC_UP             13
#define ID_BUTTON_PWM_DC_DOWN           14
#define ID_BUTTON_DEBUG                 15
#define ID_BUTTON_DETAIL                16
#define ID_BUTTON_EVALUATION            17
#define ID_BUTTON_OTP                   18
#define ID_BUTTON_OTPCAL                19
#define ID_BUTTON_TEST                  20
#define ID_BUTTON_PWM_DC_UPSMALL        21
#define ID_BUTTON_PWM_DC_DOWN2          22
#define ID_BUTTON_PWM_DC_DOWNSMALL      22
#define ID_BUTTON_PWM_DC_UP2            23
#define ID_BUTTON_PWM_DC_DOWN3          24
#define ID_BUTTON_PWM_DC_UPSMALL2       25
#define ID_BUTTON_PWM_DC_DOWNSMALL2     26
#define ID_BUTTON_INT_TEST              27
#define IDD_FANMOTOR_DIALOG             102
#define IDD_Spd_Profile                 107
#define IDD_DIALOG_SPD_PROFILE          107
#define IDR_MAINFRAME                   128
#define IDD_ABOUTBOX                    129
#define IDD_DIALOG_DEBUG                131
#define IDD_DIALOG_DETAIL               132
#define IDB_BITMAP1                     135
#define IDD_DIALOG_EVALUATION           136
#define IDD_DIALOG_OTP                  138
#define IDD_DIALOG_OTPCAL               139
#define IDD_DIALOG_TEST                 141
#define IDD_DIALOG_INT_TEST             145
#define IDD_DIALOG_TPOS                 147
#define IDD_DIALOG_AD_TORQUE            148
#define IDD_DIALOG1                     149
#define IDD_DIALOG_OTPCAL_RD            149
#define IDD_DIALOG_DacReadback          150
#define IDD_DIALOG_RELIABILITY          151
#define IDD_DIALOG_SP_RAMP              152
#define IDD_DIALOG_FW_ADTORQUE          153
#define IDD_DIALOG_TPOS_CUST            155
#define IDD_DIALOG2                     156
#define IDD_DIALOG_RELIABILITY_CUST     156
#define IDB_BITMAP2                     158
#define IDC_EDIT_ADDR                   1000
#define IDC_EDIT_SCL_FREQ               1001
#define IDC_EDIT_PWM_FREQ               1002
#define IDC_EDIT_PWM_DC                 1003
#define IDC_EDIT_MODE                   1004
#define IDC_EDIT_PWM_DC2                1005
#define IDC_EDIT_WREG_01                1008
#define IDC_BUTTON_WREG_01              1009
#define IDC_EDIT_RREG_01                1010
#define IDC_BUTTON_RREG_01              1011
#define IDC_COMBO_RREG_01               1012
#define IDC_EDIT_WREG_02                1013
#define IDC_BUTTON_WREG_02              1014
#define IDC_EDIT_RREG_02                1015
#define IDC_BUTTON_RREG_02              1016
#define IDC_COMBO_RREG_02               1017
#define IDC_EDIT_WREG_03                1018
#define IDC_BUTTON_WREG_03              1019
#define IDC_EDIT_RREG_03                1020
#define IDC_BUTTON_RREG_03              1021
#define IDC_COMBO_RREG_03               1022
#define IDC_EDIT_WREG_04                1023
#define IDC_BUTTON_WREG_04              1024
#define IDC_EDIT_RREG_04                1025
#define IDC_BUTTON_RREG_04              1026
#define IDC_COMBO_RREG_04               1027
#define IDC_EDIT_WREG_05                1028
#define IDC_BUTTON_WREG_05              1029
#define IDC_EDIT_RREG_05                1030
#define IDC_BUTTON_RREG_05              1031
#define IDC_COMBO_RREG_05               1032
#define IDC_EDIT_WREG_06                1033
#define IDC_BUTTON_WREG_06              1034
#define IDC_EDIT_RREG_06                1035
#define IDC_BUTTON_RREG_06              1036
#define IDC_COMBO_RREG_06               1037
#define IDC_EDIT_WREG_07                1038
#define IDC_BUTTON_WREG_07              1039
#define IDC_EDIT_RREG_07                1040
#define IDC_BUTTON_RREG_07              1041
#define IDC_COMBO_RREG_07               1042
#define IDC_EDIT_WREG_08                1043
#define IDC_BUTTON_WREG_08              1044
#define IDC_EDIT_RREG_08                1045
#define IDC_BUTTON_RREG_08              1046
#define IDC_COMBO_RREG_08               1047
#define IDC_EDIT_WREG_09                1048
#define IDC_BUTTON_WREG_09              1049
#define IDC_EDIT_RREG_09                1050
#define IDC_BUTTON_RREG_09              1051
#define IDC_COMBO_RREG_09               1052
#define IDC_EDIT_WREG_0a                1053
#define IDC_BUTTON_WREG_0a              1054
#define IDC_EDIT_RREG_0a                1055
#define IDC_BUTTON_RREG_0a              1056
#define IDC_COMBO_RREG_0a               1057
#define IDC_EDIT_WREG_0b                1058
#define IDC_BUTTON_WREG_0b              1059
#define IDC_EDIT_RREG_0b                1060
#define IDC_BUTTON_RREG_0b              1061
#define IDC_COMBO_RREG_0b               1062
#define IDC_EDIT_RREG_0c                1063
#define IDC_BUTTON_RREG_0c              1064
#define IDC_COMBO_RREG_0c               1065
#define IDC_EDIT_WREG_0d                1066
#define IDC_BUTTON_WREG_0d              1067
#define IDC_EDIT_RREG_0d                1068
#define IDC_BUTTON_RREG_0d              1069
#define IDC_COMBO_RREG_0d               1070
#define IDC_EDIT_RREG_0e                1071
#define IDC_BUTTON_RREG_0e              1072
#define IDC_COMBO_RREG_0e               1073
#define IDC_EDIT_RREG_0f                1074
#define IDC_BUTTON_RREG_0f              1075
#define IDC_COMBO_RREG_0f               1076
#define IDC_EDIT_WREG_10                1077
#define IDC_BUTTON_WREG_10              1078
#define IDC_EDIT_RREG_10                1079
#define IDC_BUTTON_RREG_10              1080
#define IDC_COMBO_RREG_10               1081
#define IDC_EDIT_WREG_11                1082
#define IDC_BUTTON_WREG_11              1083
#define IDC_EDIT_RREG_11                1084
#define IDC_BUTTON_RREG_11              1085
#define IDC_COMBO_RREG_11               1086
#define IDC_EDIT_WREG_12                1087
#define IDC_BUTTON_WREG_12              1088
#define IDC_EDIT_RREG_12                1089
#define IDC_BUTTON_RREG_12              1090
#define IDC_COMBO_RREG_12               1091
#define IDC_EDIT_RREG_13                1092
#define IDC_BUTTON_RREG_13              1093
#define IDC_COMBO_RREG_13               1094
#define IDC_EDIT_RREG_14                1095
#define IDC_BUTTON_RREG_14              1096
#define IDC_COMBO_RREG_14               1097
#define IDC_BUTTON_START                1098
#define IDC_BUTTON_WRITEALL             1099
#define IDC_BUTTON_STOP                 1099
#define IDC_BUTTON_READALL              1100
#define IDC_BUTTON_ACCELERATE           1100
#define IDC_COMBO_LOAD                  1101
#define IDC_BUTTON_READALL2             1101
#define IDC_BUTTON_DECELERATE2          1101
#define IDC_BUTTON_RELIABILITY_TEST     1101
#define IDC_BUTTON_READ_STATUS          1101
#define IDC_BUTTON_LOAD                 1102
#define IDC_BUTTON_RPMCOUNT             1102
#define IDC_BUTTON_ADC                  1102
#define IDC_BUTTON_PS_RELIABILITY       1102
#define IDC_COMBO_SAVE                  1103
#define IDC_BUTTON_RPMLOG               1103
#define IDC_BUTTON_READADC              1103
#define IDC_BUTTON_PWM_RELIABILITY      1103
#define IDC_BUTTON_SAVE                 1104
#define IDC_BUTTON_SPEED_PROFILE        1104
#define IDC_CHECK_FAN_EN                1105
#define IDC_EDIT_WREG_0c                1105
#define IDC_CHECK_SYN_CLAMP             1106
#define IDC_BUTTON_WREG_0c              1106
#define IDC_CHECK_VPWR_CLAMP            1107
#define IDC_EDIT_WREG_0e                1107
#define IDC_CHECK_POS_SNS               1108
#define IDC_BUTTON_WREG_0e              1108
#define IDC_CHECK_PMC_EN                1109
#define IDC_EDIT_WREG_0f                1109
#define IDC_CHECK_FAULT_SHUT            1110
#define IDC_BUTTON_WREG_0f              1110
#define IDC_CHECK_SYNC_CLAMP            1110
#define IDC_CHECK_PWM_REG               1111
#define IDC_EDIT_WREG_13                1111
#define IDC_CHECK_FAULT_SHUT2           1111
#define IDC_CHECK_SPIN_ACC              1111
#define IDC_CHECK_SYNC_CLAMP2           1111
#define IDC_CHECK_COM_SEL               1112
#define IDC_BUTTON_WREG_13              1112
#define IDC_CHECK_6S_SIN                1113
#define IDC_EDIT_WREG_14                1113
#define IDC_CHECK_TRISTATE              1114
#define IDC_BUTTON_WREG_14              1114
#define IDC_CHECK_3PH_DET               1115
#define IDC_EDIT_WREG_15                1115
#define IDC_CHECK_BEMF_FLT              1116
#define IDC_BUTTON_WREG_15              1116
#define IDC_CHECK_SP_PWR                1117
#define IDC_EDIT_RREG_15                1117
#define IDC_CHECK_VAR_DAC               1118
#define IDC_BUTTON_RREG_15              1118
#define IDC_CHECK_BLIND_SPNACCEL        1119
#define IDC_COMBO_RREG_15               1119
#define IDC_CHECK_FP_EN                 1120
#define IDC_EDIT_WREG_16                1120
#define IDC_CHECK_PWM_FREQDIV           1121
#define IDC_EDIT_RREG_16                1121
#define IDC_CHECK_OFFMSK_EN             1122
#define IDC_BUTTON_RREG_16              1122
#define IDC_COMBO_RREG_16               1123
#define IDC_CHECK_SP_CNTL_EN            1123
#define IDC_CHECK_TC_EXT                1124
#define IDC_EDIT_RREG_17                1124
#define IDC_CHECK_TSHUT_DIS             1125
#define IDC_BUTTON_RREG_17              1125
#define IDC_COMBO_REG_OVERWR            1126
#define IDC_COMBO_RREG_17               1126
#define IDC_COMBO_SCOMM                 1127
#define IDC_EDIT_WREG_18                1127
#define IDC_BUTTON_WREG_18              1128
#define IDC_CHECK_OSCCAL_MAN            1128
#define IDC_COMBO_TACHO                 1129
#define IDC_EDIT_RREG_18                1129
#define IDC_COMBO_S0S3_RPM              1130
#define IDC_BUTTON_RREG_18              1130
#define IDC_COMBO_TFREEZE               1131
#define IDC_COMBO_RREG_18               1131
#define IDC_COMBO_COMM_MASK             1132
#define IDC_EDIT_RREG_19                1132
#define IDC_COMBO_TORQUE_COARSE         1133
#define IDC_BUTTON_RREG_19              1133
#define IDC_COMBO_TORQUE_FINE           1134
#define IDC_COMBO_RREG_19               1134
#define IDC_COMBO_FREEZE_HYS            1135
#define IDC_EDIT_RREG_1a                1135
#define IDC_COMBO_BEMF_HYS              1136
#define IDC_BUTTON_RREG_1a              1136
#define IDC_COMBO_ILIMIT                1137
#define IDC_COMBO_RREG_1a               1137
#define IDC_COMBO_ILIMIT_AUTO           1138
#define IDC_EDIT_WREG_1B                1138
#define IDC_COMBO_OFF_MASK              1139
#define IDC_BUTTON_WREG_1B              1139
#define IDC_COMBO_ILIMIT_AUTO2          1140
#define IDC_EDIT_RREG_1b                1140
#define IDC_COMBO_SPIN_REV              1140
#define IDC_COMBO_S1_ISDELAY            1141
#define IDC_BUTTON_RREG_1b              1141
#define IDC_COMBO_SDISRUPT_SEL          1142
#define IDC_COMBO_RREG_1b               1142
#define IDC_COMBO_BLINDSPN_STEP         1143
#define IDC_EDIT_WREG_1C                1143
#define IDC_COMBO_BLINDSPN_COUNT        1144
#define IDC_BUTTON_WREG_1C              1144
#define IDC_COMBO_ON_MASK               1145
#define IDC_EDIT_RREG_1c                1145
#define IDC_COMBO_TS_IS                 1146
#define IDC_BUTTON_WREG_16              1146
#define IDC_COMBO_TO_S3                 1147
#define IDC_EDIT_WREG_17                1147
#define IDC_COMBO_TS_INIT               1148
#define IDC_BUTTON_WREG_17              1148
#define IDC_COMBO_TS_BLIND              1149
#define IDC_BUTTON_RREG_1c              1149
#define IDC_COMBO_TS_INITBLIND          1150
#define IDC_EDIT_WREG_19                1150
#define IDC_COMBO_OSC_OFFSET            1151
#define IDC_EDIT_WREG_1D                1151
#define IDC_COMBO_OSC_TC                1152
#define IDC_BUTTON_WREG_1D              1152
#define IDC_COMBO_TESTMUX               1153
#define IDC_EDIT_RREG_1d                1153
#define IDC_EDIT_WIN_MASK               1154
#define IDC_BUTTON_RREG_1d              1154
#define IDC_COMBO_COMSEL                1154
#define IDC_BUTTON_WIN_MASK             1155
#define IDC_COMBO_RREG_1d               1155
#define IDC_COMBO_SNSAMP_TEST           1155
#define IDC_EDIT_WIN                    1156
#define IDC_COMBO_RREG_1c               1156
#define IDC_COMBO_PG_THRESH_TEST        1156
#define IDC_BUTTON_WIN                  1157
#define IDC_EDIT_WREG_1E                1157
#define IDC_COMBO_NG_THRESH_TEST        1157
#define IDC_COMBO_LOW_DAC               1158
#define IDC_BUTTON_WREG_1E              1158
#define IDC_COMBO_SNSAMP_TEST2          1158
#define IDC_COMBO_RETRY_TIME            1158
#define IDC_COMBO_MIN_DAC               1159
#define IDC_EDIT_RREG_1e                1159
#define IDC_EDIT_LDAC                   1160
#define IDC_BUTTON_RREG_1e              1160
#define IDC_BUTTON_LDAC                 1161
#define IDC_COMBO_RREG_1e               1161
#define IDC_COMBO_TESTMODE_00           1162
#define IDC_EDIT_WREG_1F                1162
#define IDC_EDIT_HDAC                   1163
#define IDC_BUTTON_WREG_1F              1163
#define IDC_BUTTON_HDAC                 1164
#define IDC_EDIT_RREG_1f                1164
#define IDC_EDIT_HDAC_CAL               1165
#define IDC_BUTTON_RREG_1f              1165
#define IDC_EDIT_SPDAC_S1               1166
#define IDC_COMBO_RREG_1f               1166
#define IDC_BUTTON_SPDAC_S1             1167
#define IDC_EDIT_WREG_20                1167
#define IDC_BUTTON_DACUP                1168
#define IDC_BUTTON_WREG_20              1168
#define IDC_BUTTON_DACDOWN              1169
#define IDC_EDIT_RREG_20                1169
#define IDC_BUTTON_DACUP_SMALL          1170
#define IDC_BUTTON_RREG_20              1170
#define IDC_BUTTON_DACDOWN_SMALL        1171
#define IDC_COMBO_RREG_20               1171
#define IDC_EDIT_SPIN_DONE              1172
#define IDC_EDIT_WREG_2A                1172
#define IDC_EDIT_SPIN_FLT               1173
#define IDC_EDIT_WREG_22                1173
#define IDC_EDIT_TSHUT                  1174
#define IDC_EDIT_WREG_3D                1174
#define IDC_EDIT_REV                    1175
#define IDC_BUTTON_WREG_2A              1175
#define IDC_BUTTON_RSTATUS              1176
#define IDC_BUTTON_WREG_3D              1176
#define IDC_EDIT_DAC                    1177
#define IDC_BUTTON_WREG_22              1177
#define IDC_COMBO_TESTMODE_01           1178
#define IDC_EDIT_RREG_21                1178
#define IDC_COMBO_TESTMODE_10           1179
#define IDC_BUTTON_RREG_21              1179
#define IDC_EDIT_WDAC                   1180
#define IDC_COMBO_RREG_21               1180
#define IDC_BUTTON_READ_DAC             1181
#define IDC_EDIT_RREG_22                1181
#define IDC_BUTTON_WDAC                 1182
#define IDC_BUTTON_RREG_22              1182
#define IDC_BUTTON_WDACUP               1183
#define IDC_COMBO_RREG_22               1183
#define IDC_BUTTON_WDACDOWN             1184
#define IDC_EDIT_WREG_23                1184
#define IDC_BUTTON_WDACUP_SMALL         1185
#define IDC_BUTTON_WREG_23              1185
#define IDC_BUTTON_WDACDOWN_SMALL       1186
#define IDC_BUTTON_WREG_19              1186
#define IDC_EDIT_SPDAC                  1187
#define IDC_EDIT_RREG_23                1187
#define IDC_COMBO_TESTMODE_11           1188
#define IDC_BUTTON_RREG_23              1188
#define IDC_BUTTON_WMSK_UP              1189
#define IDC_COMBO_RREG_23               1189
#define IDC_EDIT_TPOS                   1190
#define IDC_EDIT_WREG_24                1190
#define IDC_BUTTON_READ_TPOS            1191
#define IDC_BUTTON_WREG_24              1191
#define IDC_EDIT_PHASE_CNT              1192
#define IDC_EDIT_RREG_24                1192
#define IDC_BUTTON_PHASE_CNT            1193
#define IDC_BUTTON_RREG_24              1193
#define IDC_BUTTON_WMSK_DOWN            1194
#define IDC_COMBO_RREG_24               1194
#define IDC_BUTTON_WIN_UP               1195
#define IDC_EDIT_WREG_25                1195
#define IDC_COMBO_POLE_PAIR             1196
#define IDC_BUTTON_WREG_25              1196
#define IDC_EDIT_SP_WINCAL              1197
#define IDC_EDIT_WREG_26                1197
#define IDC_EDIT_WINMSK_CAL             1198
#define IDC_BUTTON_RREG_25              1198
#define IDC_EDIT_WINMSK_AUTO            1199
#define IDC_COMBO_RREG_25               1199
#define IDC_BUTTON_WINMSK_AUTO          1200
#define IDC_EDIT_RREG_25                1200
#define IDC_EDIT_WINMSK_AUTOCAL         1201
#define IDC_BUTTON_WREG_26              1201
#define IDC_EDIT_SPDAC_S2               1202
#define IDC_EDIT_RREG_26                1202
#define IDC_BUTTON_SPDAC_S2             1203
#define IDC_BUTTON_RREG_26              1203
#define IDC_EDIT_SPDAC2                 1204
#define IDC_COMBO_RREG_26               1204
#define IDC_BUTTON_DACUP2               1205
#define IDC_EDIT_WREG_27                1205
#define IDC_BUTTON_DACDOWN2             1206
#define IDC_BUTTON_WREG_27              1206
#define IDC_BUTTON_DACUP_SMALL2         1207
#define IDC_EDIT_RREG_27                1207
#define IDC_BUTTON_DACDOWN_SMALL2       1208
#define IDC_BUTTON_RREG_27              1208
#define IDC_EDIT_SPDAC_S4               1209
#define IDC_COMBO_RREG_27               1209
#define IDC_BUTTON_SPDAC_S4             1210
#define IDC_EDIT_WREG_28                1210
#define IDC_EDIT_SPDAC4                 1211
#define IDC_BUTTON_WREG_28              1211
#define IDC_BUTTON_DACUP4               1212
#define IDC_EDIT_RREG_28                1212
#define IDC_BUTTON_DACDOWN4             1213
#define IDC_BUTTON_RREG_28              1213
#define IDC_BUTTON_DACUP_SMALL4         1214
#define IDC_COMBO_RREG_28               1214
#define IDC_BUTTON_DACDOWN_SMALL4       1215
#define IDC_EDIT_WREG_29                1215
#define IDC_CHECK_OSCCAL_AUTO           1216
#define IDC_BUTTON_WREG_29              1216
#define IDC_CHECK_OSC_DIS               1217
#define IDC_EDIT_RREG_29                1217
#define IDC_EDIT_TWARN                  1218
#define IDC_BUTTON_RREG_29              1218
#define IDC_EDIT_NO_SYSCLK              1219
#define IDC_COMBO_RREG_29               1219
#define IDC_EDIT_BC                     1220
#define IDC_EDIT_WREG_1A                1220
#define IDC_EDIT_TFREEZE_IN             1221
#define IDC_EDIT_SUMOUT_FFT             1221
#define IDC_BUTTON_WREG_1A              1221
#define IDC_RADIO_PWMREG_SEL            1222
#define IDC_CHECK_PWM_NONOVRLAP         1222
#define IDC_EDIT_WREG_21                1222
#define IDC_RADIO_PWMIN_SEL             1223
#define IDC_EDIT_CRC_MATCH              1223
#define IDC_BUTTON_WREG_1B2             1223
#define IDC_BUTTON_WREG_21              1223
#define IDC_RADIO_EXTDAC_SEL            1224
#define IDC_CHECK_REG_CRC_CHK_DIS       1224
#define IDC_EDIT_RPHASE_CNT             1225
#define IDC_CHECK_MODE                  1225
#define IDC_EDIT_REGCRC_CODE            1225
#define IDC_CHECK_AD_TOR                1226
#define IDC_LOAD                        1226
#define IDC_CHECK_I2C                   1226
#define IDC_EDIT_OTPCRC_CODE            1226
#define IDC_RADIO_MODE_00               1227
#define IDC_EDIT_DACW                   1227
#define IDC_RADIO_MODE_01               1228
#define IDC_EDIT_SHOWDAC                1228
#define IDC_RADIO_MODE_10               1229
#define IDC_BUTTON_DACW                 1229
#define IDC_RADIO_MODE_11               1230
#define IDC_BUTTON_DACWUP               1230
#define IDC_BUTTON_DACWDOWN             1231
#define IDC_BUTTON_WIN_DOWN             1231
#define IDC_CHECK_OTP_CRC_CHK_DIS_TEST  1231
#define IDC_BUTTON_DACWUPSMALL          1232
#define IDC_BUTTON_WINAUTO_UP           1232
#define IDC_BUTTON_DACWDOWNSMALL        1233
#define IDC_BUTTON_WINAUTO_DOWN         1233
#define IDC_EDIT_MAX_DAC                1234
#define IDC_BUTTON_MSKAUTO_UP           1234
#define IDC_EDIT_MIN_DAC                1235
#define IDC_BUTTON_MSKAUTO_DOWN         1235
#define IDC_CHECK_VARDAC_EN             1236
#define IDC_EDIT_REFCOUNT               1236
#define IDC_CHECK_ADTOR_EN              1237
#define IDC_BUTTON_REFCOUNT             1237
#define IDC_COMBO_VARDAC_CNT            1238
#define IDC_EDIT_REFCOUNTR              1238
#define IDC_RPM_COUNT                   1239
#define IDC_BUTTON_REFCOUNTUP           1239
#define IDC_EDIT_RPM_COUNT              1240
#define IDC_BUTTON_REFCOUNTDOWN         1240
#define IDC_FAN                         1241
#define IDC_BUTTON_REFCOUNTUP_SMALL     1241
#define IDC_BUTTON_DACR                 1242
#define IDC_BUTTON_REFCOUNTDOWN_SMALL   1242
#define IDC_COMBO_ILIMIT_BRAKE          1243
#define IDC_READ_EVAL                   1243
#define IDC_COMBO_ILIMIT_BRAKE2         1244
#define IDC_COMBO_BBS_RANGE             1244
#define IDC_RADIO_OTP1                  1244
#define IDC_COMBO_ILIMIT_BRKMASK        1244
#define IDC_COMBO_MINSP                 1245
#define IDC_RADIO_OTPCAL                1245
#define IDC_COMBO_SPIN_TIME             1246
#define IDC_BUTTON_BURN_OTP1            1246
#define IDC_COMBO_SPIN_STEP             1247
#define IDC_PROGRESS1                   1247
#define IDC_RADIO_BLIND_SPIN_DIS        1248
#define IDC_CHECK_PASS1                 1248
#define IDC_RADIO_BLIND_SPIN_EN         1249
#define IDC_CHECK_FAIL1                 1249
#define IDC_COMBO_SPIN_INIT             1250
#define IDC_CHECK_OTPCALDONE            1250
#define IDC_CHECK_DIRECT_SPN            1251
#define IDC_EDIT_CALREG0E               1251
#define IDC_BUTTON_FILELOAD             1251
#define IDC_COMBO_LOW                   1252
#define IDC_COMBO_CALREG0E              1252
#define IDC_BUTTON_FILESAVE             1252
#define IDC_COMBO_TACHPIN_SEL           1253
#define IDC_BUTTON_SAVE_FILE_OTPCAL     1253
#define IDC_EDIT_PWMIN_FINAL            1254
#define IDC_EDIT_CALREG11               1254
#define IDC_EDIT_TORA                   1254
#define IDC_EDIT_TARGET_SPD             1255
#define IDC_COMBO_CALREG11              1255
#define IDC_COMBO_TORA                  1255
#define IDC_CHECK_TOR_HYS_DIS           1256
#define IDC_EDIT_CALREG13               1256
#define IDC_BUTTON_OTPCAL               1256
#define IDC_EDIT_FILETORA               1256
#define IDC_BUTTON_MANUAL_IS            1257
#define IDC_COMBO_CALREG13              1257
#define IDC_PROGRESS2                   1257
#define IDC_EDIT_FILETORB               1257
#define IDC_RADIO_HSS                   1258
#define IDC_EDIT_CALREG15               1258
#define IDC_CHECK_PASSCAL               1258
#define IDC_EDIT_FILETORC               1258
#define IDC_RADIO_LSS                   1259
#define IDC_COMBO_CALREG14              1259
#define IDC_COMBO_CALREG15              1259
#define IDC_CHECK_FAILCAL               1259
#define IDC_EDIT_FILETORD               1259
#define IDC_EDIT_FBRES                  1260
#define IDC_EDIT_REFRES                 1261
#define IDC_EDIT_FILETORE               1261
#define IDC_EDIT_SENRES                 1262
#define IDC_CHECK_DLLOTP                1262
#define IDC_EDIT_FILETORF               1262
#define IDC_EDIT_SENGAIN                1263
#define IDC_CHECK_FFOTP                 1263
#define IDC_EDIT_FILETORG               1263
#define IDC_BUTTON_SET_ILIMIT           1264
#define IDC_CHECK_TRIPHASEOTP           1264
#define IDC_EDIT_FILETORH               1264
#define IDC_CHECK_CLKMON_EN             1265
#define IDC_CHECK_PMCOTP                1265
#define IDC_COMBO_ILIMIT2               1266
#define IDC_COMBO_ILIMIT_MAX            1266
#define IDC_CHECK_PWMOVROTP             1266
#define IDC_CHECK_SKIP_S2_TEST          1266
#define IDC_CHECK_REG2P5FB_EN           1267
#define IDC_EDIT_TORB                   1267
#define IDC_CHECK_VARDACOTP             1267
#define IDC_CHECK_TSHUTDIS              1268
#define IDC_COMBO_TORB                  1268
#define IDC_CHECK_OFFBRKOTP             1268
#define IDC_CHECK_USEREG                1269
#define IDC_EDIT_TORC                   1269
#define IDC_COMBO_OSCTCOTP              1269
#define IDC_COMBO_OSCTC                 1270
#define IDC_COMBO_TORC                  1270
#define IDC_COMBO_OSCOFFOTP             1270
#define IDC_CHECK_OTP1DONE              1271
#define IDC_COMBO_CHROMSEL              1271
#define IDC_CHECK_TCEXT                 1271
#define IDC_CHECK_OTPCAL_DONE           1272
#define IDC_EDIT_TORD                   1272
#define IDC_EDIT_REFSPEED               1273
#define IDC_COMBO_TORD                  1273
#define IDC_COMBO_PINSEL                1273
#define IDC_CHECK_BEMF_FILTER_EN        1273
#define IDC_BUTTON_REFSPEED             1274
#define IDC_EDIT_TORE                   1274
#define IDC_CHECK_RETRY_DIS             1274
#define IDC_CHECK_SKIP_S2               1274
#define IDC_RADIO_1PP                   1275
#define IDC_COMBO_TORE                  1275
#define IDC_CHECK_SWAP_BC               1275
#define IDC_COMBO_PWM_LOW               1275
#define IDC_BRIDGE_LISTBOX              1275
#define IDC_RADIO_4PP                   1276
#define IDC_EDIT_TORF                   1276
#define IDC_CHECK_TRIPHASE_DET          1276
#define IDC_COMBO_PWM_FLOAT             1276
#define IDC_DEVICE_LISTBOX              1276
#define IDC_CHECK_SLOW_RESPONSE         1277
#define IDC_COMBO_TORF                  1277
#define IDC_BUTTON_SAVE_OTPCAL          1277
#define IDC_COMBO_IS_DELAY              1278
#define IDC_EDIT_TORG                   1278
#define IDC_CHECK_PWMFLOATDIS           1278
#define IDC_CHECK_DLL_EN                1279
#define IDC_COMBO_TORG                  1279
#define IDC_EDIT_ADC                    1279
#define IDC_CHECK_OTP_CRC_CHK_DIS       1279
#define IDC_CHECK_FF_EN                 1280
#define IDC_EDIT_TORH                   1280
#define IDC_CHECK_CLKMONEN              1280
#define IDC_COMBO_PWMFREQ               1280
#define IDC_CHECK_FF_S6_EN              1281
#define IDC_COMBO_TORH                  1281
#define IDC_COMBO_PWMFREQ_OTP           1281
#define IDC_CHECK_LEVEL_OVERFLOW        1282
#define IDC_COMBO_TORQUE_FILELOAD       1282
#define IDC_CHECK_DUAL_PROFILE_EN       1282
#define IDC_EDIT_SUMOUT_FF              1283
#define IDC_COMBO_TORQUE_FILESAVE       1283
#define IDC_CHECK_TRIPLE_PROFILE_EN     1283
#define IDC_EDIT_SUMOUT_FF_TEST         1284
#define IDC_COMBO_PG_THRESH             1284
#define IDC_EDIT_RELY_CNT               1285
#define IDC_COMBO_NG_THRESH             1285
#define IDC_EDIT_RELY_ON                1286
#define IDC_EDIT_RELY_OFF               1287
#define IDC_CHECK_FAN_EN_OFF_BRK_DIS    1287
#define IDC_RADIO_HEX                   1288
#define IDC_CHECK_HP_ALARM_DIS          1288
#define IDC_EDIT_PSCnt                  1288
#define IDC_RADIO_PERCENT               1289
#define IDC_COMBO_RETRY_TIMEOTP         1289
#define IDC_COMBO1                      1289
#define IDC_COMBO_MARGIN_RD_EN          1289
#define IDC_EDIT_PSOn                   1289
#define IDC_CHECK_PWM_AVG_EN            1289
#define IDC_COMBO_TorCoarseA            1289
#define IDC_COMBO_TPOS_ILIMIT_IS        1289
#define IDC_RADIO_SPDAC_S1              1290
#define IDC_CHECK_RETRY_TRISTATEOTP     1290
#define IDC_EDIT_PSOff                  1290
#define IDC_CHECK_NEW_STABLE_SPD_EN     1290
#define IDC_COMBO_TorFineA              1290
#define IDC_RADIO_SPDAC_S2              1291
#define IDC_CHECK_RETRY_ILIM_BRKOTP     1291
#define IDC_EDIT_PWMCnt                 1291
#define IDC_COMBO_TorCoarseB            1291
#define IDC_RADIO_SPDAC_S4              1292
#define IDC_COMBO_CheckOTPCALFile       1292
#define IDC_EDIT_PWMOn                  1292
#define IDC_COMBO_TorFineB              1292
#define IDC_EDIT_RPMCOUNT               1293
#define IDC_BUTTON_CheckOTPCALFile      1293
#define IDC_EDIT_PWMOff                 1293
#define IDC_COMBO_TorCoarseC            1293
#define IDC_EDIT_MINSP                  1294
#define IDC_COMBO_CheckOTP1File         1294
#define IDC_COMBO_TorFineC              1294
#define IDC_EDIT_MINSP_PERCENT          1295
#define IDC_BUTTON1                     1295
#define IDC_BUTTON_CheckOTP1File        1295
#define IDC_BUTTON_UpdatePWM1           1295
#define IDC_BUTTON_Firmware_Version     1295
#define IDC_BUTTON_ReadTPOS             1295
#define IDC_BUTTON_Measure              1295
#define IDC_BUTTON_DacReadback          1295
#define IDC_COMBO_TorCoarseD            1295
#define IDC_BUTTON_TPOS_TEST            1295
#define IDC_BUTTON_MINSP                1296
#define IDC_EDIT1                       1296
#define IDC_EDIT_UpdatePWM1             1296
#define IDC_EDIT_Firmware_Version       1296
#define IDC_EDIT_TPOS1                  1296
#define IDC_EDIT_Step                   1296
#define IDC_EDIT_Loop_Count             1296
#define IDC_EDIT_nLoop                  1296
#define IDC_COMBO_TorFineD              1296
#define IDC_EDIT_PERSEC                 1297
#define IDC_EDIT_TPOS2                  1297
#define IDC_EDIT_SettleTime             1297
#define IDC_EDIT_TimePeriod             1297
#define IDC_COMBO_TorCoarseE            1297
#define IDC_EDIT_test                   1297
#define IDC_EDIT_FORSEC                 1298
#define IDC_EDIT_TPOS3                  1298
#define IDC_EDIT_SettleTime2            1298
#define IDC_EDIT_MaxDac                 1298
#define IDC_EDIT_PSnLoop                1298
#define IDC_BUTTON_Rtest                1298
#define IDC_CHECK_FAN_EN_OFF_BRK        1299
#define IDC_EDIT_TPOS4                  1299
#define IDC_EDIT_PSTimePeriod           1299
#define IDC_EDIT_MinDac                 1299
#define IDC_BUTTON_Wtest                1299
#define IDC_CHECK_PWM_FLOAT_DIS         1300
#define IDC_EDIT_TPOS5                  1300
#define IDC_EDIT_PWMnLoop               1300
#define IDC_COMBO_TorFineE              1300
#define IDC_COMBO_PWM_FLOAT_DETAIL      1301
#define IDC_EDIT_TPOS6                  1301
#define IDC_EDIT_PWMTimePeriod          1301
#define IDC_COMBO_TorCoarseF            1301
#define IDC_COMBO_PWM_LOW_DETAIL        1302
#define IDC_EDIT_TPOS_DELTA             1302
#define IDC_COMBO__TorFineF             1302
#define IDC_COMBO_TorFineF              1302
#define IDC_COMBO_HT                    1303
#define IDC_EDIT_TPOS1_star             1303
#define IDC_COMBO_TorCoarseG            1303
#define IDC_COMBO_LT                    1304
#define IDC_EDIT_TPOS2_star             1304
#define IDC_COMBO_TorFineG              1304
#define IDC_COMBO_MT                    1305
#define IDC_EDIT_TPOS3_star             1305
#define IDC_COMBO_TorCoarseH            1305
#define IDC_EDIT_LOW                    1306
#define IDC_EDIT_TPOS4_star             1306
#define IDC_COMBO_TorFineH              1306
#define IDC_EDIT_MID                    1307
#define IDC_EDIT_TPOS5_star             1307
#define IDC_EDIT_LOW_PERCENT            1308
#define IDC_EDIT_TPOS6_star             1308
#define IDC_EDIT_MID_PERCENT            1309
#define IDC_EDIT_TorCoarseA             1309
#define IDC_EDIT_TPOS_ILIMIT_IS         1309
#define IDC_BUTTON_ReadTPOS2            1309
#define IDC_BUTTON_SCOMM_TPOS           1309
#define IDC_EDIT_HT                     1310
#define IDC_EDIT_TorFineA               1310
#define IDC_EDIT_HT_PERCENT             1311
#define IDC_EDIT_TorCoarseB             1311
#define IDC_EDIT_LT                     1312
#define IDC_EDIT_TorFineB               1312
#define IDC_EDIT_LT_PERCENT             1313
#define IDC_EDIT_TorCoarseC             1313
#define IDC_EDIT_MT1                    1314
#define IDC_EDIT_TorFineC               1314
#define IDC_EDIT_MIT1_PERCENT           1315
#define IDC_EDIT_TorCoarseD             1315
#define IDC_EDIT_MID2                   1316
#define IDC_EDIT_TorFineD               1316
#define IDC_EDIT_MID2_PERCENT           1317
#define IDC_EDIT_TorCoarseE             1317
#define IDC_EDIT_MT2                    1318
#define IDC_EDIT_TorFineE               1318
#define IDC_EDIT_MIT2_PERCENT           1319
#define IDC_EDIT_TorCoarseF             1319
#define IDC_EDIT_INCRE_PERCENT          1320
#define IDC_EDIT_TorFineF               1320
#define IDC_EDIT_EFFECTIVE_SDISRUPT     1321
#define IDC_EDIT_TorCoarseG             1321
#define IDC_COMBO_PWMIN_FS              1322
#define IDC_EDIT_TorFineG               1322
#define IDC_CHECK_TACHPIN_INV           1323
#define IDC_BUTTON2                     1323
#define IDC_BUTTON_AdtorExtract         1323
#define IDC_BUTTON_Tacho                1323
#define IDC_CHECK_RETRY_ILIM_BRK        1324
#define IDC_CHECK_OTP1DONE_Test         1324
#define IDC_CHECK_RETRY_TRISTATE        1325
#define IDC_EDIT_TorCoarseH             1325
#define IDC_EDIT_TorFineH               1326
#define IDC_EDIT_MINDAC_CLAMP           1326
#define IDC_EDIT_OSCTCTEST              1327
#define IDC_BUTTON_MINDAC_CLAMP         1327
#define IDC_EDIT_OSCOFFTEST             1328
#define IDC_EDIT_MINDAC_CLAMP_RD        1328
#define IDC_EDIT_PINSELTEST             1329
#define IDC_EDIT_PWM_LOWTEST            1330
#define IDC_EDIT_PWM_FLOATTEST          1331
#define IDC_EDIT_PWMFREQTEST            1332
#define IDC_EDIT_CHROMSELTEST           1333
#define IDC_EDIT_RETRY_TIMETEST         1334
#define IDC_BUTTON_ReadOTPCAL           1335
#define IDC_CHECK_SWAPBC                1336
#define IDC_ANIMATE1                    1337
#define IDC_CHECK_OTPCALDONE_Test       1337
#define IDC_EDIT2                       1338
#define IDC_EDIT_Tacho                  1338
#define IDC_EDIT_LowVolt                1338
#define IDC_EDIT_TO_S3                  1338
#define IDC_BUTTON_DialogSpeedProfile   1339
#define IDC_EDIT_Tacho2                 1339
#define IDC_EDIT_Rtest                  1339
#define IDC_RADIO_Inc                   1340
#define IDC_RADIO_Dec                   1341
#define IDC_BUTTON_TPOS                 1343
#define IDC_BUTTON_AdTorque             1344
#define IDC_BUTTON_OTPCAL_Read          1345
#define IDC_CHECK_Tacho                 1346
#define IDC_BUTTON_DAC_Readback         1346
#define IDC_CHECK_FinalDac              1347
#define IDC_BUTTON_Reliability          1347
#define IDC_CHECK_Current               1348
#define IDC_RADIO_RegMode               1348
#define IDC_BUTTON_SpdRamp              1348
#define IDC_RADIO_PSMode                1349
#define IDC_CHECK_Dac                   1349
#define IDC_RADIO_PwminLowMode          1350
#define IDC_CHECK_Current2              1350
#define IDC_CHECK_Volt                  1350
#define IDC_RADIO_RegLoop               1353
#define IDC_RADIO_RegTime               1354
#define IDC_CHECK_SelLowVolt            1355
#define IDC_CHECK_Sel12Volt             1356
#define IDC_CHECK_SelHighVolt           1357
#define IDC_EDIT_HighVolt               1358
#define IDC_EDIT_CurrLimit              1359
#define IDC_RADIO_PWMCY                 1360
#define IDC_RADIO_PWMFG                 1361
#define IDC_EDIT_RegOn                  1362
#define IDC_EDIT_RegOff                 1363
#define IDC_EDIT_RegCnt                 1364
#define IDC_BUTTON_REG_RELIABILITY      1365
#define IDC_RADIO_PSLoop                1366
#define IDC_RADIO_PWM_REG               1366
#define IDC_RADIO_PSTime                1367
#define IDC_RADIO_PWM_IN                1367
#define IDC_RADIO_PWMLoop               1368
#define IDC_CHECK_DAC_B2B               1368
#define IDC_RADIO_PWMTime               1369
#define IDC_CHECK2                      1369
#define IDC_CHECK_FinalDac_B2B          1369
#define IDC_RADIO_PWM_FuncGen           1370
#define IDC_CHECK_Fault                 1371
#define IDC_RADIO_Loop                  1374
#define IDC_EDIT_LoopNo                 1375
#define IDC_EDIT_LoopN                  1375
#define IDC_EDIT_Ts                     1376
#define IDC_CHECK1                      1378
#define IDC_CHECK_StopFan               1378
#define IDC_CHECK_GAIN_SEL              1378
#define IDC_CHECK_FWAdTor               1379
#define IDC_BUTTON_FW_ADTORQUE          1379
#define IDC_EDIT_SettleT                1380
#define IDC_COMBO_TPOS_ILIMIT_IS1       1381
#define IDC_EDIT_TPOS_ILIMIT_IS1        1382

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1383
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
